### ISSUE TITLE
AllocRingBuffer paniced (index out of bounds) when iterating

### ISSUE THREAD

**Issue by d2weber** [NULLx76/ringbuffer#60]
To reproduce:
```
$ cat Cargo.toml 
[dependencies]
ringbuffer = "0.8.4"

$ cat src/main.rs 
use ringbuffer::{AllocRingBuffer, RingBufferExt, RingBufferWrite};

fn main() {
    let mut b = AllocRingBuffer::with_capacity_power_of_2(3);
    for i in 0..10 {
        println!("{i}");
        b.push(3);
        for _ in b.iter() {
            {}
        }
    }
}
$ cargo run
   Compiling bg v0.1.0 (/tmp/bg)
    Finished dev [unoptimized + debuginfo] target(s) in 0.36s
     Running `target/debug/bg`
0
1
2
3
4
5
6
7
8
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 8', /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/ringbuffer-0.8.4/src/with_alloc.rs:210:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 8', /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/ringbuffer-0.8.4/src/with_alloc.rs:104:41
stack backtrace:
   0:     0x564a0d64d1bd - std::backtrace_rs::backtrace::libunwind::trace::h33935f50be729600
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564a0d64d1bd - std::backtrace_rs::backtrace::trace_unsynchronized::h85350690f550732a
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564a0d64d1bd - std::sys_common::backtrace::_print_fmt::hef50877fc14d4570
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x564a0d64d1bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h864135c3b342f033
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x564a0d66753c - core::fmt::write::hcb503b08861a7383
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/fmt/mod.rs:1197:17
   5:     0x564a0d64b391 - std::io::Write::write_fmt::hf066c210584f89df
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/io/mod.rs:1672:15
   6:     0x564a0d64e845 - std::sys_common::backtrace::_print::h8c59e37a3ed34e23
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x564a0d64e845 - std::sys_common::backtrace::print::h90aab6df99a2db90
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x564a0d64e845 - std::panicking::default_hook::{{closure}}::h09cc51c67f7f7d05
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:295:22
   9:     0x564a0d64e566 - std::panicking::default_hook::he0bf4d235e26ea03
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:314:9
  10:     0x564a0d64edd6 - std::panicking::rust_panic_with_hook::ha977288eb720b249
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:698:17
  11:     0x564a0d64ecc7 - std::panicking::begin_panic_handler::{{closure}}::h963e19a72c1e136f
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:588:13
  12:     0x564a0d64d674 - std::sys_common::backtrace::__rust_end_short_backtrace::h846b3986734acf64
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x564a0d64e9f9 - rust_begin_unwind
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:584:5
  14:     0x564a0d6326b3 - core::panicking::panic_fmt::h5c0d1820488dd088
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/panicking.rs:142:14
  15:     0x564a0d6325f2 - core::panicking::panic_bounds_check::h3e141b02948de1e3
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/panicking.rs:84:5
  16:     0x564a0d6344ee - <usize as core::slice::index::SliceIndex<[T]>>::index_mut::h17e35db1a4691212
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/slice/index.rs:248:14
  17:     0x564a0d636746 - core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut::hf4155266dc5e34f6
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/slice/index.rs:30:9
  18:     0x564a0d636c25 - <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut::h6ba303ffaccf035d
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/alloc/src/vec/mod.rs:2636:9
  19:     0x564a0d6340ca - <ringbuffer::with_alloc::AllocRingBuffer<T> as ringbuffer::ringbuffer_trait::RingBufferRead<T>>::dequeue::hbc955638b7d7fa34
                               at /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/ringbuffer-0.8.4/src/with_alloc.rs:104:41
  20:     0x564a0d632c71 - <ringbuffer::ringbuffer_trait::iter::RingBufferDrainingIterator<T,RB> as core::iter::traits::iterator::Iterator>::next::h8acbb3b1df576d51
                               at /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/ringbuffer-0.8.4/src/ringbuffer_trait.rs:316:13
  21:     0x564a0d632ca8 - core::iter::traits::iterator::Iterator::fold::h8a2e2d9ebe31a167
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/iter/traits/iterator.rs:2369:29
  22:     0x564a0d632d72 - core::iter::traits::iterator::Iterator::for_each::h19e1c81b66e44bad
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/iter/traits/iterator.rs:787:9
  23:     0x564a0d6336bd - <ringbuffer::with_alloc::AllocRingBuffer<T> as core::ops::drop::Drop>::drop::h83f1b3f77ac9ffad
                               at /home/d/.cargo/registry/src/github.com-1ecc6299db9ec823/ringbuffer-0.8.4/src/with_alloc.rs:48:9
  24:     0x564a0d633533 - core::ptr::drop_in_place<ringbuffer::with_alloc::AllocRingBuffer<i32>>::h8c4cd8271789765a
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/ptr/mod.rs:487:1
  25:     0x564a0d6363f7 - bg::main::hd52aba1ee4453884
                               at /tmp/bg/src/main.rs:12:1
  26:     0x564a0d6334eb - core::ops::function::FnOnce::call_once::h0d3af57f79cb72a2
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/ops/function.rs:248:5
  27:     0x564a0d63317e - std::sys_common::backtrace::__rust_begin_short_backtrace::h8d920146be0a6822
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/sys_common/backtrace.rs:122:18
  28:     0x564a0d6370e1 - std::rt::lang_start::{{closure}}::h7f6fcbd969b8074e
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/rt.rs:145:18
  29:     0x564a0d64872e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfaf7c58d89ec8d8b
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/core/src/ops/function.rs:280:13
  30:     0x564a0d64872e - std::panicking::try::do_call::h09d0703a282a3a1c
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:492:40
  31:     0x564a0d64872e - std::panicking::try::h980d16309c043650
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:456:19
  32:     0x564a0d64872e - std::panic::catch_unwind::h5f9ed0d74f2601fe
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panic.rs:137:14
  33:     0x564a0d64872e - std::rt::lang_start_internal::{{closure}}::h3663c482286e7e54
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/rt.rs:128:48
  34:     0x564a0d64872e - std::panicking::try::do_call::h457692961e2c4baa
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:492:40
  35:     0x564a0d64872e - std::panicking::try::hf684a2d1878fa0d5
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panicking.rs:456:19
  36:     0x564a0d64872e - std::panic::catch_unwind::h9f35d9add9e38060
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/panic.rs:137:14
  37:     0x564a0d64872e - std::rt::lang_start_internal::h04b289f2c2c53cd9
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/rt.rs:128:20
  38:     0x564a0d6370b0 - std::rt::lang_start::h08ce42a86a6d47d9
                               at /rustc/efd358333ac55ca50f786ca1ab841c003bfdfff0/library/std/src/rt.rs:144:17
  39:     0x564a0d6365bc - main
  40:     0x7fc2cbbe0083 - __libc_start_main
                               at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  41:     0x564a0d6328ae - _start
  42:                0x0 - <unknown>
thread panicked while panicking. aborting.
Aborted (core dumped)
```

**Comment by jonay2000** [comment]
Fixed by #59
